trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build
  displayName: 'Build and Push Docker Image'
  variables:
    dockerUsername: 'riya652'
    dockerPassword: 'N/cjZZjbBsD;8e6'

  steps:
  - checkout: self
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-21-jdk  # Install Java 21
      java -version  # Verify Java installation
    displayName: 'Set up JDK 21'
  - script: |
      mvn clean install
    displayName: 'Build with Maven'
  - script: |
      docker login -u $(dockerUsername) -p $(dockerPassword)
    displayName: 'Login to Docker Hub'
  - script: |
      docker build -t riya652/devops:springboot-images-new1 .
      docker push riya652/devops:springboot-images-new1
    displayName: 'Build & push Docker image'
